media:
  input: src/assets
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/data/blog
    view:
      fields: [ title, draft, pubDatetime , author, tags, slug ]
    fields:
      - name: author
        label: Author
        type: select
        options:
          values:
            - value: eugene
              label: Eugene Venger
            - value: karina
              label: Karina Venger
        required: true
      - { name: pubDatetime, label: Date of Publishing, type: date, required: true }
      - { name: modDatetime, label: Date of Modifying, type: date}
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - name: tags
        label: Tags
        type: select
        list: true
        options:
          values:
            - value: cooking
              label: Cooking
            - value: personal
              label: Personal
            - value: family
              label: Family
        required: true
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }